### ISSUE TITLE
Request: Bluetooth Serial

### ISSUE THREAD

**Issue by SphaeroX** [meisben/easyEEZYbotARM#1]
Hello,

im working on an controller with an ESP32 (Wemos Lolin32), so i wanted to ask you if it is possible to change your program to blueooth or if you can program a function to switch to bluetooth?

I'm also working on the ESP32 being able to record program sequences with a tech procedure.

**Comment by meisben** [comment]
Hi! - i'm really sorry but that's beyond the scope of this repository currently. You're really welcome to fork the repository. PyBluez (https://pypi.org/project/PyBluez/) looks to be a great library to achieve this aim. I'm happy to support with any questions you have that relate to the current code. And to consider any pull requests. Thanks!
