### ISSUE TITLE
Kinematics equations

### ISSUE THREAD

**Issue by jillazalat** [meisben/easyEEZYbotARM#2]
Hello, do you have the kinematics equations posted anywhere?

**Comment by meisben** [comment]
Hi - I'm v sorry I'm late in reply to this. I missed the issue notification. 
I haven't got the equations posted somewhere currently, but I'm happy to post them if it's helpful for you still? 
Thanks

**Comment by jillazalat** [comment]
Hi there - that's okay, I no longer need the equations. Thank you regardless!

**Comment by meisben** [comment]
Hi - Just to note that I completed these because someone else requested them. 

If you do need them you can find them [here](https://github.com/meisben/easyEEZYbotARM/tree/master/docs/kinematics)

Thanks - all the best
