### ISSUE TITLE
Can't Compile Code

### ISSUE THREAD

**Issue by LucaCraft89** [meisben/easyEEZYbotARM#3]
Hi, I cannot compline my .ino even after importing all the libraries Here is The error
`C:\Users\lucac\AppData\Local\Temp\ccQF83uZ.ltrans0.ltrans.o: In function `global constructors keyed to 65535_0_easyEEZYbotARM_Arduino_Communication.ino.cpp.o.2327':
<artificial>:(.text.startup+0xfe): undefined reference to `ServoEasing::ServoEasing(unsigned char, TwoWire*)'
<artificial>:(.text.startup+0x10c): undefined reference to `ServoEasing::ServoEasing(unsigned char, TwoWire*)'
<artificial>:(.text.startup+0x11a): undefined reference to `ServoEasing::ServoEasing(unsigned char, TwoWire*)'
<artificial>:(.text.startup+0x128): undefined reference to `ServoEasing::ServoEasing(unsigned char, TwoWire*)'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1`

**Comment by AnNguyen2332** [comment]
Hello Lucas, did you solve yhe problem yet? I got the same problem with you.

**Comment by AnNguyen2332** [comment]
Hello Lucas, I solved the problem!

Try: `#include "ServoEasing.hpp"` instead of `#include "ServoEasing.h"`

Hope it's useful for you!

**Comment by meisben** [comment]
Thanks for flagging this. And apologies for my late response.

I have now addressed this in [this ](https://github.com/meisben/easyEEZYbotARM/commit/74fdef2b7e2b1e409cfac3729df992d284b2d6d2) commit

Thanks
