### ISSUE TITLE
How to control robot arm with python + arduino

### ISSUE THREAD

**Issue by kenanman** [meisben/easyEEZYbotARM#4]
i have verified and uploaded the code to arduino, and setup everything, but i dont know how to control the servos. if you could tell me please would be very helpful.
edit: i have tried the python examples. when i open "make the eezybotarm move", it just sends 2 commands to the servos to buzz, then if i click anything it shuts off.

**Comment by meisben** [comment]
Hi, 

To debug this you could use the arduino IDE (make sure baud rate is 9600)

You can send a message to the arduino using the IDE serial monitor in the format 

`msg = "<LED,90,90,90,90,1000,1000,1000,1000>"  # default message`

You can see the message format description on line 52 [here](https://github.com/meisben/easyEEZYbotARM/blob/master/python_packages/easyEEZYbotARM/serial_communication.py)

You can see the meaning of each part of the message on line 197 [here](https://github.com/meisben/easyEEZYbotARM/blob/master/arduino_sketches/easyEEZYbotARM_Arduino_Communication/easyEEZYbotARM_Arduino_Communication.ino)

- The first item in the message can take either the value LED or BUZZ (which either blinks the LED or buzzes the optional buzzer [if connected])
- The next 4 items in the message are joint angles for the robot arm
- The last 4 items in the message are joint speeds for the robot arm

This is the default position for the joints

`msg = "<LED,90,90,90,90,1000,1000,1000,1000>"  # default message`

If you send a message like this one in the serial monitor to the arduino, you should see the LED blink, and al the joints (servos) of the robot arm move to the angle 60 degrees

`<LED,60,60,60,60,1000,1000,1000,1000>`

Let me know how you get on

**Comment by kenanman** [comment]
thank you so much bro now its working fine

**Comment by meisben** [comment]
No worries! :+1:
